In [ ]:
# !pip install -U bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 13.6 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [ ]:
!mkdir -p ~/.kaggle/
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d gowrishankarp/newspaper-text-summarization-cnn-dailymail

Dataset URL: https://www.kaggle.com/datasets/gowrishankarp/newspaper-text-summarization-cnn-dailymail
License(s): CC0-1.0
Downloading newspaper-text-summarization-cnn-dailymail.zip to /content
 94% 474M/503M [00:01<00:00, 358MB/s]
100% 503M/503M [00:01<00:00, 430MB/s]

In [ ]:
from datasets import load_dataset

In [ ]:
!unzip /content/newspaper-text-summarization-cnn-dailymail.zip

Archive:  /content/newspaper-text-summarization-cnn-dailymail.zip
replace cnn_dailymail/test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace cnn_dailymail/train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace cnn_dailymail/validation.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [ ]:
data_files = {
    "train": "/content/cnn_dailymail/train.csv",
    "test": "/content/cnn_dailymail/test.csv",
    "validation": "/content/cnn_dailymail/validation.csv"
}
dataset = load_dataset("csv", data_files=data_files)
print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'article', 'highlights'],
        num_rows: 287113
    })
    test: Dataset({
        features: ['id', 'article', 'highlights'],
        num_rows: 11490
    })
    validation: Dataset({
        features: ['id', 'article', 'highlights'],
        num_rows: 13368
    })
})

In [ ]:
def format_data(data):
  instruction = "Summarize the following news article:\n\n"
  return {
      "text": f"{instruction}{data['article']}\n\n###Summary:{data['highlights']}"
  }

In [ ]:
dataset = dataset.map(format_data)

Map:   0%|          | 0/287113 [00:00<?, ? examples/s]

Map:   0%|          | 0/11490 [00:00<?, ? examples/s]

Map:   0%|          | 0/13368 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'article', 'highlights', 'text'],
        num_rows: 287113
    })
    test: Dataset({
        features: ['id', 'article', 'highlights', 'text'],
        num_rows: 11490
    })
    validation: Dataset({
        features: ['id', 'article', 'highlights', 'text'],
        num_rows: 13368
    })
})

In [ ]:
# import transformers as tf
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer, DataCollatorForLanguageModeling, BitsAndBytesConfig
import peft
import torch

In [ ]:
model_name="Qwen/Qwen2.5-1.5B-Instruct"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_function(examples):
    encoded = tokenizer(
        examples["text"],            # <---- FIXED, no [0]
        truncation=True,
        padding="max_length",
        max_length=512,
    )

    # labels = input_ids, with padding masked
    labels = []
    for ids in encoded["input_ids"]:
        labels.append([
            id if id != tokenizer.pad_token_id else -100
            for id in ids
        ])

    encoded["labels"] = labels
    return encoded

tokenized_dataset = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/287113 [00:00<?, ? examples/s]

Map:   0%|          | 0/11490 [00:00<?, ? examples/s]

Map:   0%|          | 0/13368 [00:00<?, ? examples/s]

In [ ]:
tokenized_dataset = tokenized_dataset.remove_columns(['id', 'article', 'highlights', 'text'])

In [ ]:
tokenized_dataset.save_to_disk("/content/tokenized_dataset")

Saving the dataset (0/4 shards):   0%|          | 0/287113 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/11490 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/13368 [00:00<?, ? examples/s]

In [ ]:
!zip -r /content/tokenized_dataset.zip /content/tokenized_dataset

  adding: content/tokenized_dataset/ (stored 0%)
  adding: content/tokenized_dataset/train/ (stored 0%)
  adding: content/tokenized_dataset/train/data-00000-of-00004.arrow (deflated 74%)
  adding: content/tokenized_dataset/train/state.json (deflated 60%)
  adding: content/tokenized_dataset/train/data-00001-of-00004.arrow (deflated 74%)
  adding: content/tokenized_dataset/train/data-00002-of-00004.arrow (deflated 74%)
  adding: content/tokenized_dataset/train/data-00003-of-00004.arrow (deflated 74%)
  adding: content/tokenized_dataset/train/dataset_info.json (deflated 70%)
  adding: content/tokenized_dataset/test/ (stored 0%)
  adding: content/tokenized_dataset/test/state.json (deflated 37%)
  adding: content/tokenized_dataset/test/dataset_info.json (deflated 70%)
  adding: content/tokenized_dataset/test/data-00000-of-00001.arrow (deflated 74%)
  adding: content/tokenized_dataset/dataset_dict.json (deflated 2%)
  adding: content/tokenized_dataset/validation/ (stored 0%)
  adding: content/tokenized_dataset/validation/state.json (deflated 37%)
  adding: content/tokenized_dataset/validation/dataset_info.json (deflated 70%)
  adding: content/tokenized_dataset/validation/data-00000-of-00001.arrow (deflated 74%)

In [ ]:
sample_train_tokenized = tokenized_dataset["train"].shuffle(seed=42).select(range(5000))
sample_validation_tokenized = tokenized_dataset["validation"].shuffle(seed=42).select(range(1000))

In [ ]:
len(sample_train_tokenized['labels'][0])

512

In [ ]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

In [ ]:
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    )

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training
model = prepare_model_for_kbit_training(model)
lora_config = LoraConfig(
    r = 8,
    lora_alpha = 32,
    target_modules = ["q_proj", "v_proj","k_proj","o_proj"],
    lora_dropout = 0.05,
    task_type = TaskType.CAUSAL_LM,
    bias = "none"
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 2,179,072 || all params: 1,545,893,376 || trainable%: 0.1410

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
training_arg = TrainingArguments(
    output_dir = "/content/drive/MyDrive/qwen3_lora_final",
    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 8,
    optim = "paged_adamw_32bit",
    save_steps = 100,
    logging_steps = 10,
    learning_rate = 1e-5,
    fp16 = True,
    bf16 = False,
    max_grad_norm = 0.3,
    num_train_epochs =3,
    eval_strategy="steps",
    eval_steps=100,
    gradient_checkpointing=True,
    report_to="none",
    save_strategy="steps",
    save_total_limit=3,
    remove_unused_columns=False,
)

In [ ]:
data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

In [ ]:
trainer = Trainer(
    model = model,
    args = training_arg,
    train_dataset = sample_train_tokenized,
    eval_dataset = sample_validation_tokenized,
    data_collator = data_collator,
)

In [ ]:
model.config.use_cache = False  # Disable cache to use gradient checkpointing

In [ ]:
trainer.train()

KeyboardInterrupt:

In [ ]:
trainer.train(resume_from_checkpoint="/content/drive/MyDrive/qwen3_lora_final/checkpoint-200")

TrainOutput(global_step=939, training_loss=1.8590576549688467, metrics={'train_runtime': 7006.4949, 'train_samples_per_second': 2.141, 'train_steps_per_second': 0.134, 'total_flos': 6.079540757004288e+16, 'train_loss': 1.8590576549688467, 'epoch': 3.0})

In [ ]:
save_path = "/content/drive/MyDrive/qwen3_lora_progress"

trainer.model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

('/content/drive/MyDrive/qwen3_lora_progress/tokenizer_config.json',
 '/content/drive/MyDrive/qwen3_lora_progress/chat_template.jinja',
 '/content/drive/MyDrive/qwen3_lora_progress/tokenizer.json')